[versions]
accompanistPermissions = "0.37.3"
accompanistSwiperefresh = "0.36.0"
activityCompose = "1.10.1"
agp = "9.2.1"
androidxMaterial3 = "1.3.2"
cameraCore = "1.6.1"
converterGson = "3.0.0"
converterMoshi = "2.9.0"
datastorePreferences = "1.2.1"
desugar_jdk_libs = "2.1.5"
firebaseAnalytics = "22.4.0"
firebaseAnalyticsKtx = "22.4.0"
firebaseBom = "33.12.0"
firebaseBomVersion = "34.13.0"
firebaseInstallationsKtx = "18.0.0"
kotlin = "2.2.10"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lifecycleRuntimeCompose = "2.10.0"
material = "1.12.0"
constraintlayout = "2.2.0"
material3 = "1.3.2"
material3AdaptiveNavigation = "1.0.0-alpha04"
material3AdaptiveNavigationSuite = "1.4.0-alpha13"
material3Pullrefresh = "1.0.0-alpha20"
material3Version = "1.4.0"
material3WindowSizeClass = "1.3.2"
materialIconsExtendedVersion = "1.6.7"
materialVersion = "1.8.0"
navigationFragmentKtx = "2.7.7"
navigationUiKtx = "2.7.7"
playServicesWearable = "20.0.1"
retrofit = "2.9.0"
roomCompiler = "2.8.4"
roomRuntime = "2.8.4"
textRecognition = "16.0.1"
ui = "1.6.8"
androidbrowserhelper = "2.6.0"
tracing = "1.3.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-material3-pullrefresh = { module = "androidx.compose.material3:material3-pullrefresh", version.ref = "material3Pullrefresh" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version = "1.6.7" }


# androidx-material3-adaptive-navigation = { module = "androidx.compose.material3:material3-adaptive-navigation", version.ref = "material3AdaptiveNavigation" }

androidx-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3AdaptiveNavigationSuite" }

androidx-material3-v132 = { module = "androidx.compose.material3:material3", version.ref = "androidxMaterial3" }
androidx-material3-v140 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationFragmentKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-compiler-v250 = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-installations-ktx = { module = "com.google.firebase:firebase-installations-ktx", version.ref = "firebaseInstallationsKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServicesWearable" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidbrowserhelper = { group = "com.google.androidbrowserhelper", name = "androidbrowserhelper", version.ref = "androidbrowserhelper" }
androidx-tracing = { group = "androidx.tracing", name = "tracing", version.ref = "tracing" }
text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "textRecognition" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
